FROM debian_base AS debian-from
FROM ubuntu_base AS ubuntu-from
FROM centos_base AS centos-from
FROM centos6_base AS centos6-base
FROM alpine_base AS alpine-from

LABEL MAINTAINER="WaterBolik@163.com"
