# https://hub.docker.com/r/jenkins/jenkins/
# To use the latest LTS: docker pull jenkins/jenkins:lts
# To use the latest weekly: docker pull jenkins/jenkins
version: '2.1'

services:

  jenkins:
    container_name: jenkins
    build: alpine-jenkins
    # build: https://github.com/realpython/flask-microservices-users.git
    # image: jenkins/jenkins
    # image: jenkins/jenkins:alpine
    # image: jenkins/jenkins:lts
    # image: jenkins/jenkins:lts-alpine
    volumes:
      - ./jenkins_home:/var/jenkins_home
    ports:
      - '8080:8080'
      - '50000:50000'
    # environment:
    #   - JAVA_OPTS=-Dhudson.footerURL=http://mycompany.com


# $ docker run --rm --name jenkins -p 8080:8080 -p 50000:50000 -v jenkins_home:/var/jenkins_home jenkins/jenkins
# $ docker run --rm --name jenkins-lts -p 8080:8080 -p 50000:50000 -v jenkins_home:/var/jenkins_home jenkins/jenkins:lts
# $ docker run --rm --name jenkins-blueocean -d -p 8080:8080 -v jenkins-data:/var/jenkins_home -v /var/run/docker.sock:/var/run/docker.sock jenkinsci/blueocean
# $ docker exec -it jenkins-blueocean bash
# $ docker logs jenkins-blueocean
