# https://store.docker.com/images/python

version: '2'

networks:
  bridge:
    driver: bridge

services:
  python2:
    # build: alpine-python2
    image: alpine-python2
    # image: python:2.7.14-alpine3.6
    networks:
      - bridge   

  python3:
    # build: alpine-python3
    image: alpine-python3
    # image: python:3.6.3-alpine3.6
    networks:
      - bridge

  python-demo:
    build: python-demo
    volumes:
      - ./python-demo/app:/usr/src/app
    networks:
      - bridge
